C2DEVEL-14659: Add tag name from last recovery point to protected resource model
C2Devel/botocore pull request #113
Opened 2024-04-23 08:36 UTC by RudeZwloki7

Closes issue: C2DEVEL-14659

2024-04-24 14:32 UTC, kinazarov1999 requested changes

2024-04-24 14:32 UTC, kinazarov1999 commented on botocore/data/backup/2018-11-15/service-2.json
> +          "documentation":"<p>The tag name of resource retrieved from last recovery point.</p>"
`the last recovery point.`

2024-06-19 09:46 UTC, funkmajer commented
TIW

2024-07-08 14:31 UTC, Sharpeye90 commented
@RudeZwloki7 rebase pls

2024-07-08 16:07 UTC, RudeZwloki7 commented
@Sharpeye90 done

2024-07-09 09:59 UTC, merged