ec2: add VirtualizationType,HighAvailable to LaunchTemplateData
C2Devel/botocore pull request #37
Opened 2022-05-17 10:31 UTC by DavidDzgoev

2022-05-17 10:43 UTC, kszakharov approved these changes

2022-05-18 09:19 UTC, No-Rib requested changes

2022-05-20 14:19 UTC, No-Rib approved these changes

2022-06-22 13:45 UTC, aeko-empt commented
Reopen in PR: https://github.com/C2Devel/botocore/pull/42

2022-06-22 13:45 UTC, closed without merging